[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/sonde-go"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[constraint]]
  branch = "sts"
  source = "github.com/govau/go-kinesis"
  name = "github.com/sendgridlabs/go-kinesis"

[prune]
  go-tests = true
  unused-packages = true
